#!/usr/bin/env bash

# $1 - readme
function render_markdown_to_html {
  # escape escaping characters
  if [[ $(uname) == "Darwin" ]]; then
    content=$(
      cat "$1"                                          \
        | sed 's/\\/\\\\/g'                             \
        | sed 's/"/\\"/g'                               \
        | sed $'s/\t/\\\\t/g'                           \
        | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\n/g' \
    )
  else
    content=$(
      cat "$1"                          \
        | sed 's/\\/\\\\/g'             \
        | sed 's/"/\\"/g'               \
        | sed 's/\t/\\t/g'              \
        | sed ':a;N;$!ba;s/\n/\\n/g'    \
    )
  fi

  # network call to GitHub API
  json="{\"text\":\"$content\",\"mode\":\"gfm\",\"context\":\"$USERNAME/swift-algorithm-club\"}"
  echo -e "$(curl -s --data "$json" -u $USERNAME:$TOKEN https://api.github.com/markdown)"
}

# $1 - comment
function push_to_gh_pages {
  git checkout -b gh-pages
  git add .
  git commit -m "$1"
  git push -f https://$TOKEN@github.com/$USERNAME/swift-algorithm-club.git gh-pages
}

# download github systax highlight stylesheet
echo "> Downloading github-light.css..."
curl -s -O https://raw.githubusercontent.com/primer/github-syntax-light/master/lib/github-light.css

# if index.html does not exist, create one;
# otherwise, empty its content.
if [[ -z index.html ]]; then
  touch index.html
else
  > index.html
fi

# iterate immediate directories
find . -maxdepth 1 -type d | while read folder; do
  readme=''

  # get the right extension for the README file if there is one
  if [[ -f $folder/README.md ]]; then readme="$folder/README.md"; fi
  if [[ -f $folder/README.markdown ]]; then readme="$folder/README.markdown"; fi

  # exclude the repository's README
  if [[ !(-z $readme) && ($readme != "./README.markdown") ]]; then
    name=$(basename "$folder")
    echo "> Generating $name/index.html..."

    cat > "$folder/index.html" << EOF
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="../github-light.css">
  <style>
    body {
      font-size: 18px;
    }
    code {
        padding: 0.2em;
        margin: 0;
        font-size: 85%;
        background-color: #f6f8fa;
        line-height: 1.45;
        border-radius: 3px
    }
    pre code {
        padding: 0px;
        background-color: transparent;
    }
    .highlight {
      margin: 0px;
      padding: 0px 16px;
      font-size: 85%;
      line-height: 1.45;
      overflow: auto;
      background-color: #f6f8fa;
      border-radius: 3px;
    }
  </style>
</head>
<body>
    $(render_markdown_to_html "$readme")
</body>
</html>
EOF
    # temporarily write the list of HTML filenames to the main index.html
    echo "$lists<li><a href=\"$name/index.html\">$name</a></li>" >> index.html
  fi
done

echo "<!DOCTYPE html><body><h1>Swift Algorithm</h1><ul>$(echo -n $(cat index.html))</ul></body></html>" > index.html

# push to gh-pages
if [[ $CI = true ]]; then push_to_gh_pages "Generated by TravisCI on $(date +%D)"; fi
