var radix = RadixTree()
var radixWiki = RadixTree()

radixWiki.insert("romanus")
radixWiki.insert("rubicundus")
radixWiki.insert("rubicon")
radixWiki.insert("romane")
radixWiki.insert("ruber")
radixWiki.insert("rubens")
radixWiki.insert("romulus")
radixWiki.insert("start")
radixWiki.insert("shoot")
radixWiki.insert("shit")
radixWiki.insert("starch")
radixWiki.insert("steven")

radixWiki.insert("compute")
radixWiki.insert("compatible")
radixWiki.insert("construction")
radixWiki.insert("coral")
radixWiki.insert("crude")
radixWiki.insert("chalk")
radixWiki.insert("chime")
radixWiki.insert("courting")
radixWiki.insert("courted")

radixWiki.insert("rubicunduses")

radixWiki.printTree()

print("FIND TESTS")
print(radixWiki.find("courts"))
print(radixWiki.find("rubicunduses"))
print(radixWiki.find(""))