var radix = RadixTree()
var radix2 = RadixTree()
var radixWiki = RadixTree()

print("-------------------------------------------------")
radix.printTree()
print("--------------------------------------------------")
radix.insert( "courting" )
radix.printTree()
print("-------------------------------------------------")
radix.insert( "coral" )
radix.printTree()
print("--------------------------------------------------")
radix.insert( "courted" )
radix.printTree()
print("---------------------------------------------------")
print( radix.insert( "corals") )
radix.printTree()

print( radixWiki.insert("romanus") )
print( radixWiki.insert("rubicundus") )
print( radixWiki.insert("rubicon") )
print( radixWiki.insert("romane") )
print( radixWiki.insert("ruber") )
print( radixWiki.insert("rubens") )
print( radixWiki.insert("romulus") )
radixWiki.insert("start")
radixWiki.insert("shoot")
radixWiki.insert("shit")
radixWiki.insert("starch")
radixWiki.insert("steven")

radixWiki.insert("compute")
radixWiki.insert("compatible")
radixWiki.insert("construction")
radixWiki.insert("coral")
radixWiki.insert("crude")
radixWiki.insert("chalk")
radixWiki.insert("chime")
radixWiki.insert("courting")
radixWiki.insert("courted")

print("PRINT TEST-------------------------------")
radixWiki.printTree()

// let h = radix.height()
// let h2 = radix2.height()
// let hwiki = radixWiki.height()
// print("Height of tree: \(h)")
// print("height of second tree: \(h2)")
// print("Height of wikipedia tree: \(hwiki)")

// print(radixWiki.root.level())
// print(radixWiki.root.children[0].level())
// print(radixWiki.root.children[0].children[0].level())
// print(radixWiki.root.children[0].children[0].children[0].level())

// print("\t\t\t\t\t\ttest")
// print("PRINT TEST-------------------------------")
// radixWiki.printTree()

// print("PRINT TEST-------------------------------")
// radix.printTree()