
print("tests")


var T: Trie = Trie()
T.insert("Hello")
T.insert("Hi")
T.insert("Hey")
T.insert("Hallo")
T.insert("Henry")
T.insert("YELLO")
var U: Trie = Trie(wordList: Set(["Hey", "HO", "hello", "yolo"]))
var V: Trie = T.merge(U)
//T.printTrie()
//U.printTrie()
//V.printTrie()
print(V.getWords())
V.removeAll()
//V.printTrie()
/*T.insert("Hello")
T.insert("Hey")
T.insert("YOLO")
T.insert("Him")
assert(T.count() == 4, "Count function failed")
assert(T.contains("Hey") == true)
assert(T.contains("Hello") == true)
print("trying remove")
T.remove("Him")
assert(T.count() == 3)
assert(T.contains("Him") == false, "Test failed")
assert(T.wordList.count == 3)*/

//T.printTrie()
//print(T.find(""))
print(T.findPrefix("H"))
